### ISSUE TITLE
Archive this repo

### ISSUE THREAD

**Issue by szabgab** [Hamakor/python_il_site#5]
If I am not mistaken this is an old version of what is now [here](https://gitlab.com/hamakor/python.org.il/).
If this is not in use any more, it might be a good idea to "archive" this repo.

**Comment by shaib** [comment]
I've checked -- the Gitlab project started with some "initial backup of python.org.il" which seems to have little-to-no relation to the contents of this repository (maybe it's just the output -- @uda who created it in 2019 may know).

Anyway, my plan was to change the default branch here to `use-lektor` before archiving, so that the most rececnt code in this repo is presented for anyone who looks. I consulted with @AmitAronovitch -- he wants to see first if there's anything of value here that isn't in Gitlab, and maybe add a reference to the new project.

I'm setting myself a reminder to do the add-message-and-archive part in a week, if he doesn't get to it.

**Comment by szabgab** [comment]
I've just added [this](https://gitlab.com/hamakor/python.org.il/-/commit/6bcffc3e29194720609f6a62fc5eea54331e3ee5) for the archeologists.

**Comment by uda** [comment]
The "initial backup" was from what python.org.il was serving at the time, I think this repo was an attempt to move that site into a generated site using lektor but it never completed

**Comment by shaib** [comment]
(one needs to close open issues before archiving, so...)
